upstream backend_cluster { # 3 servidores de backend
    least_conn; # balanceamento de carga - distribui os acessos entre os servidores de backend
    server api1-backend:3000 max_fails=3 fail_timeout=30s; # failover - se falhar 3 vezes é considerado fora do ar, reinicia a tentativa após 30 segundos
    server api2-backend:3000 max_fails=3 fail_timeout=30s;
    server api3-backend:3000 max_fails=3 fail_timeout=30s;
}

# cria limite de requisiçõse por segundo para cada IP
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

server {
    listen 80;

    access_log /var/log/nginx/access.log; # logs de acesso
    error_log /var/log/nginx/error.log; # logs de erro

    gzip on; # comprime os arquivos enviando mais rápido para o navegador e economiza internet
    gzip_types text/plain text/css application/javascript application/json; # tipos de arquivos que serão comprimidos

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host; # envia o dominio e host acessados para o backend (log)
        proxy_set_header X-Real-IP $remote_addr; # envia o IP real do cliente para o backend (log)
    }   

    location /api/ {
        limit_req zone=api_limit; # usa a limitação de requisições na api

        proxy_pass http://backend_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;

        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
    }

    location /admin/ {
        root /usr/share/nginx/html;
        index dashboard.html;
        try_files $uri $uri/ /admin/dashboard.html;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /nginx-status { # status do nginx, como requisições e conexões ativas
        stub_status;
    }

    location /health {
        return 200 '{"status":"ok","server":"nginx"}';
        add_header Content-Type application/json;
        #allow 127.0.0.1; # permite acesso apenas do localhost da minha máquina
        #deny all; # nega acesso de outros IPs
    }
}