# SERVIDOR HTTPS (PORTA 443)
server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    # Define quais versões de protocolo são aceitas (mais seguras)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Define quais tipos de criptografia serão usados (somente fortes)
    ssl_ciphers HIGH:!aNULL:!MD5;

    # FRONTEND
    location / {
        proxy_pass http://frontend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API (BACKEND COM LOAD BALANCE)
    location /api/ {
        proxy_pass http://backend_cluster;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Guarda o histórico de IPs (proxy → backend)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ADMIN
    location /admin/ {
        proxy_pass http://admin/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# REDIRECIONAMENTO HTTP → HTTPS
server {
    # Escuta na porta 80 (HTTP)
    listen 80;

    # Redireciona tudo para HTTPS
    return 301 https://$host$request_uri;

    # $host → domínio (localhost)
    # $request_uri → caminho completo (/api, /admin, etc)
}